# Enable Flutter's recommended lints and add a couple of lightweight rules.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - .dart_tool/**
    - build/**
    - "**/*.g.dart"

linter:
  rules:
    avoid_print: true  # prefer using a logger
