name: Android Release (APK on tags)

on:
  push:
    tags:
      - "v*"

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (Android)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"
          channel: "stable"
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --no-pub

      - name: Build debug APK
        run: flutter build apk --debug --no-tree-shake-icons

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.ref_name }}.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error

      - name: Build release APK (unsigned)
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-${{ github.ref_name }}.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error

